# Generated by Django 2.2.1 on 2019-05-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='person',
            new_name='c_name',
        ),
    ]
